# Generated by Django 5.1.2 on 2024-10-10 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminPage', '0001_initial'),
        ('TeacherPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('adminresponse', models.TextField(blank=True)),
                ('submitdate', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherPage.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student')),
            ],
        ),
    ]
