# Generated by Django 5.1.2 on 2025-01-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0002_alter_student_enrolldate_alter_teacher_hiredate'),
        ('StudentPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPage.student'),
        ),
    ]
