# Generated by Django 5.1.2 on 2025-01-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolldate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hiredate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
